[workspace]
resolver ="2"

members = ["base64", "matasano-ops", "matasano-util"]

[workspace.lints]
rust.rust_2018_idioms = { level = "warn" }

clippy.correctness.level = "warn"
clippy.perf.level = "warn"
clippy.disallowed_methods.level = "warn"

[workspace.dependencies]
base64 = { path = "./base64" }
matasano-ops = { path = "./.matasano-ops" }
matasano-util = { path = "./matasano-util" }
