[package]
name = "matasano-challenges"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
matasano-bitwise.workspace = true
matasano-util.workspace = true

[lints]
workspace = true
